#!/bin/bash
# Checks the status of the VPN connection and updates vpn_status as necessary

is_vpn_running=$(pgrep openvpn)   
if [[ -z "$is_vpn_running" ]]
then
   echo "Disabled" > /home/jd/.vpn/vpn_status
   if [ -f /home/jd/.vpn/vpn_active ] 
   then
      rm /home/jd/.vpn/vpn_active
   fi
   else
      echo "Active" > /home/jd/.vpn/vpn_status
      if [ ! -f /home/jd/.vpn/vpn_active ]; then
         touch /home/jd/.vpn/vpn_active
      fi
fi
