#!/bin/bash

status=$(pgrep openvpn)
   
if [[ -z "$status" ]]; then
	echo "Disabled" > /home/jd/.vpn/vpn_status
	
	if [ -f /home/jd/.vpn/vpn_active ]; then
           rm /home/jd/.vpn/vpn_active
	fi
	
	else
	   echo "Active" > /home/jd/.vpn/vpn_status
	   
	   if [ ! -f /home/jd/.vpn/vpn_active ]; then
	      touch /home/jd/.vpn/vpn_active
	   fi
fi
