#!/bin/bash
#
# /* hideme* /
# This script will effectively hide your activity online.
# It starts a logless VPN connection and spoofs the ethernet MAC address

msg_green() {
	printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

msg_error() {
	printf "${RED}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
GREEN="${BOLD}$(tput setaf 2)"
RED="${BOLD}$(tput setaf 1)"

script_error="-1"
real_mac_address=`cat /home/jd/.vpn/real_mac_address`

startvpn

if [ ! -f /home/jd/.vpn/mac_spoofed ]
then
	spoofmac
else
	msg_error "MAC already spoofed!"
	script_error="true"
fi

checkvpn
vpn_status=`cat /home/jd/.vpn/vpn_status`

if [ "$vpn_status" == "Active" ]
then
   if [ "$mac_address" != "$real_mac_address" ]
	then
	   if [ "$script_error" != "true" ]
		then
         msg_green "Cloaking successful."
     	else
         msg_error "Errors occured."
     	fi
	fi				
fi

