#!/bin/bash
# This script will effectively hide your activity online.
# It starts a logless VPN connection and spoofs the ethernet MAC address

msg_green() {
	printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

msg_error() {
	printf "${RED}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
GREEN="${BOLD}$(tput setaf 2)"
RED="${BOLD}$(tput setaf 1)"

startvpn

real_mac_address=`cat /home/jd/.vpn/real_mac_address`

if [ ! -f /home/jd/.vpn/mac_spoofed ]
then
   msg_green "Spoofing MAC address..."
	sudo macchanger -r eno1
	resetmacinfo
else
	msg_green "MAC already spoofed!"
	resetmacinfo
fi

checkvpn

vpn_status=`cat /home/jd/.vpn/vpn_status`

if [ "$vpn_status" == "Active" -a "$mac_address" != "$real_mac_address" ]
then
	msg_green "Success!"
else
	msg_error "Errors occured, cloaking failed."
fi

