#!/bin/bash
# This script will start the VPN client for a US EAST server and update conky info as necessary 

msg_green() {
	printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

msg_error() {
	printf "${RED}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
GREEN="${BOLD}$(tput setaf 2)"
RED="${BOLD}$(tput setaf 1)"

if [ "$(id -u)" != "0" ]
then
   openvpn_status=$(pgrep openvpn)
   if [[ -z "$openvpn_status" ]]
   then
      msg_green "Starting US East VPN connection..."
      sudo systemctl start openvpn@useast.service
      
		msg_green "Sleeping 5 seconds to accomodate IP info update for conky..."
      sleep 5
	
		checkvpn
		vpn_status=`cat /home/jd/.vpn/vpn_status`
		openvpn_status=$(pgrep openvpn)

		if [ "$vpn_status" = "Active" -a ! -z "$openvpn_status" ]
		then
         msg_green "VPN is now running."
 			touch /home/jd/.vpn/vpn_active
			resetipinfo
		else
		   msg_error "VPN failed to start!"
			resetipinfo
		fi
   else
      msg_error "VPN already running!"
   fi
else
   msg_error "Do not run this script as root, it will break things :("
fi
