#!/bin/bash
# This script will stop the VPN and update conky ipinfo as necessary

if [ "$(id -u)" != "0" ]
then
   status=$(pgrep openvpn)
   if [[ -z "$status" ]] 
   then
      echo "VPN is not running!"
   else
      sudo systemctl stop openvpn@useast.service
      echo "Sleeping 5 seconds to accomodate IP info update for conky..."
      sleep 5
      resetipinfo
      
      if [ -f /home/jd/.vpn/vpn_active ]
      then
         rm /home/jd/.vpn/vpn_active
      fi
   fi
   else
      echo "Do not run this script as root, it will break things :("
fi
