#!/bin/bash

# /* stopvpn */
# This scripts halts the connection to the 
# US East private internet access VPN server

msg_green() {
	printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

msg_error() {
	printf "${RED}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
GREEN="${BOLD}$(tput setaf 2)"
RED="${BOLD}$(tput setaf 1)"

if [ "$(id -u)" != "0" ]
then
   status=$(pgrep openvpn)
   if [[ -z "$status" ]] 
   then
      msg_error "VPN is not running!"
   else
      msg_green "Stopping US East VPN connection..."
      sudo systemctl stop openvpn@useast.service
      
		msg_green "Sleeping 5 seconds to accomodate IP info update for conky..."
      sleep 5
		
		checkvpn
		vpn_status=`cat /home/jd/.vpn/vpn_status`
		openvpn_status=$(pgrep openvpn)
      
		if [ "$vpn_status" = "Disabled" -a -z "$openvpn_status" ] 
		then
		   msg_green "VPN service halted."
		   resetipinfo
		else
		   msg_error "VPN service not halted!"
			resetipinfo
		fi
      
      if [ -f /home/jd/.vpn/vpn_active ]
      then
         rm /home/jd/.vpn/vpn_active
      fi
   fi
   else
      msg_error "Do not run this script as root, it will break things :("
fi
